# Generated by Django 5.0 on 2025-11-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
